### ISSUE TITLE
I suggest you to use correct REST API resource naming, please see article 

### ISSUE THREAD

**Issue by vasylenkoArtem** [AlexWhitehorse/MockBilling#1]
https://github.com/AlexWhitehorse/MockBilling/blob/7673a529413b9c2e7a4e6d56ff48a63da7dbb64b/MockBilling/MockBilling/Controllers/UserController.cs#L21

@AlexWhitehorse 
https://restfulapi.net/resource-naming/

**Comment by vasylenkoArtem** [comment]
> https://github.com/AlexWhitehorse/MockBilling/blob/7673a529413b9c2e7a4e6d56ff48a63da7dbb64b/MockBilling/MockBilling/Controllers/UserController.cs#L21
> 
> https://restfulapi.net/resource-naming/

)))))))))

**Comment by AlexWhitehorse** [comment]
@vasylenkoArtem Thanks for your advice. I will take this into account in further development.
